CKEDITOR.dialog.add("base64imageDialog",function(b){function q(a){if("string"==typeof a&&a){var d=new Image;d.onload=function(){if(this.width>b.config.kepMaximalisSzelessege||this.height>b.config.kepMaximalisMagassaga)f.getElement().setHtml(b.config.kepTulNagyFelbontasuMsg),CKEDITOR.dialog.getCurrent().disableButton("ok");else{CKEDITOR.dialog.getCurrent().enableButton("ok");f.getElement().setHtml("");null==c||null==h?(e.setValueOf("tab-properties","width",this.width),e.setValueOf("tab-properties",
"height",this.height),k=1,0<this.height&&0<this.width&&(k=this.width/this.height),0>=k&&(k=1)):h=c=null;this.id=b.id+"previewimage";this.setAttribute("style","max-width:400px;max-height:100px;");this.setAttribute("alt","");try{var d=f.getElement().$;d&&d.appendChild(this)}catch(a){}}};d.onerror=function(){f.getElement().setHtml("")};d.onabort=function(){f.getElement().setHtml("")};d.src=a}else f.getElement().setHtml("")}function r(){f.getElement().setHtml("");var a=e.getContentElement("tab-source",
"file"),d=null;try{d=a.getInputElement().$}catch(b){d=null}d&&"files"in d&&d.files&&0<d.files.length&&d.files[0]&&(!("type"in d.files[0])||d.files[0].type.match("image.*"))&&FileReader&&(f.getElement().setHtml("Betöltés..."),a=new FileReader,a.onload=function(a){return function(a){f.getElement().setHtml("");q(a.target.result)}}(d.files[0]),a.onerror=function(){f.getElement().setHtml("")},a.onabort=function(){f.getElement().setHtml("")},a.readAsDataURL(d.files[0]))}function n(a){var d=e.getContentElement("tab-properties",
"width").getValue(),b=e.getContentElement("tab-properties","height").getValue(),f="px",g="px";0<=d.indexOf("%")&&(f="%");0<=b.indexOf("%")&&(g="%");d=parseInt(d,10);b=parseInt(b,10);isNaN(d)&&(d=0);isNaN(b)&&(b=0);var c="px";"width"==a?("%"==f&&(c="%"),b=Math.round(d/k)):("%"==g&&(c="%"),d=Math.round(b*k));"%"==c&&(d+="%",b+="%");e.getContentElement("tab-properties","width").setValue(d);e.getContentElement("tab-properties","height").setValue(b)}function p(a){var b=a.getValue(),e="";0<=b.indexOf("%")&&
(e="%");b=parseInt(b,10);isNaN(b)&&(b=0);a.setValue(b+e)}var e=null,a=null,c=null,h=null,f=null,k=1,l=!0,t=[{type:"file",id:"file",label:"",onChange:function(){r()}},{type:"html",id:"preview",html:(new CKEDITOR.template('\x3cdiv style\x3d"text-align:center;"\x3e\x3c/div\x3e')).output()}];return{title:b.lang.common.image,minWidth:450,minHeight:180,onLoad:function(){this.getContentElement("tab-source","url");f=this.getContentElement("tab-source","preview");this.getContentElement("tab-properties","lock").getInputElement().on("click",
function(){(l=this.getValue()?!0:!1)&&n("width")},this.getContentElement("tab-properties","lock"));this.getContentElement("tab-properties","width").getInputElement().on("keyup",function(){l&&n("width")});this.getContentElement("tab-properties","height").getInputElement().on("keyup",function(){l&&n("height")});this.getContentElement("tab-properties","vmargin").getInputElement().on("keyup",function(){p(this)},this.getContentElement("tab-properties","vmargin"));this.getContentElement("tab-properties",
"hmargin").getInputElement().on("keyup",function(){p(this)},this.getContentElement("tab-properties","hmargin"));this.getContentElement("tab-properties","border").getInputElement().on("keyup",function(){p(this)},this.getContentElement("tab-properties","border"))},onShow:function(){f.getElement().setHtml("");e=this;h=c=null;k=1;l=!0;(a=b.getSelection())&&(a=a.getSelectedElement());a&&"img"===a.getName()||(a=null);e.setValueOf("tab-properties","lock",l);e.setValueOf("tab-properties","vmargin","0");e.setValueOf("tab-properties",
"hmargin","0");e.setValueOf("tab-properties","border","0");e.setValueOf("tab-properties","align","none");if(a){"string"==typeof a.getAttribute("width")&&(c=a.getAttribute("width"));"string"==typeof a.getAttribute("height")&&(h=a.getAttribute("height"));null!=c&&null!=h||!a.$||(c=a.$.width,h=a.$.height);null!=c&&null!=h&&(e.setValueOf("tab-properties","width",c),e.setValueOf("tab-properties","height",h),c=parseInt(c,10),h=parseInt(h,10),k=1,!isNaN(c)&&!isNaN(h)&&0<h&&0<c&&(k=c/h),0>=k&&(k=1));"string"==
typeof a.getAttribute("src")&&(0===a.getAttribute("src").indexOf("data:")?(r("base64"),q(a.getAttribute("src"))):e.setValueOf("tab-source","url",a.getAttribute("src")));"string"==typeof a.getAttribute("alt")&&e.setValueOf("tab-properties","alt",a.getAttribute("alt"));"string"==typeof a.getAttribute("hspace")&&e.setValueOf("tab-properties","hmargin",a.getAttribute("hspace"));"string"==typeof a.getAttribute("vspace")&&e.setValueOf("tab-properties","vmargin",a.getAttribute("vspace"));"string"==typeof a.getAttribute("border")&&
e.setValueOf("tab-properties","border",a.getAttribute("border"));if("string"==typeof a.getAttribute("align"))switch(a.getAttribute("align")){case "top":case "text-top":e.setValueOf("tab-properties","align","top");break;case "baseline":case "bottom":case "text-bottom":e.setValueOf("tab-properties","align","bottom");break;case "left":e.setValueOf("tab-properties","align","left");break;case "right":e.setValueOf("tab-properties","align","right")}e.selectPage("tab-properties")}},onOk:function(){var c=
"";try{c=CKEDITOR.document.getById(b.id+"previewimage").$.src}catch(d){c=""}if("string"==typeof c&&null!=c&&""!==c){var f=a?a:b.document.createElement("img");f.setAttribute("src",c);f.setAttribute("alt",e.getValueOf("tab-properties","alt").replace(/^\s+/,"").replace(/\s+$/,""));var c={width:["width","width:#;","integer",1],height:["height","height:#;","integer",1],vmargin:["vspace","margin-top:#;margin-bottom:#;","integer",0],hmargin:["hspace","margin-left:#;margin-right:#;","integer",0],align:["align",
""],border:["border","border:# solid black;","integer",0]},h=[],g,k,l,m;for(m in c){k=l=g=e.getValueOf("tab-properties",m);unit="px";if("align"==m)switch(g){case "top":case "bottom":c[m][1]="vertical-align:#;";break;case "left":case "right":c[m][1]="float:#;";break;default:g=null}"integer"==c[m][2]&&(0<=g.indexOf("%")&&(unit="%"),g=parseInt(g,10),isNaN(g)?g=null:g<c[m][3]&&(g=null),null!=g&&("%"==unit?(l=g+"%",k=g+"%"):(l=g,k=g+"px")));null!=g&&(f.setAttribute(c[m][0],l),h.push(c[m][1].replace(/#/g,
k)))}0<h.length&&f.setAttribute("style",h.join(""));a||b.insertElement(f);b.plugins.imageresize&&b.plugins.imageresize.resize(b,f,800,800)}},contents:[{id:"tab-source",label:b.lang.common.generalTab,elements:t},{id:"tab-properties",label:b.lang.common.advancedTab,elements:[{type:"text",id:"alt",label:b.lang.base64image.alt},{type:"hbox",widths:["15%","15%","70%"],children:[{type:"text",width:"45px",id:"width",label:b.lang.common.width},{type:"text",width:"45px",id:"height",label:b.lang.common.height},
{type:"checkbox",id:"lock",label:b.lang.base64image.lockRatio,style:"margin-top:18px;"}]},{type:"hbox",widths:["23%","30%","30%","17%"],style:"margin-top:10px;",children:[{type:"select",id:"align",label:b.lang.common.align,items:[[b.lang.common.notSet,"none"],[b.lang.common.alignTop,"top"],[b.lang.common.alignBottom,"bottom"],[b.lang.common.alignLeft,"left"],[b.lang.common.alignRight,"right"]]},{type:"text",width:"45px",id:"vmargin",label:b.lang.base64image.vSpace},{type:"text",width:"45px",id:"hmargin",
label:b.lang.base64image.hSpace},{type:"text",width:"45px",id:"border",label:b.lang.base64image.border}]}]}]}});