/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
(function(){function u(a){for(var g=0,n=0,d=0,f,c=a.$.rows.length;d<c;d++){f=a.$.rows[d];for(var b=g=0,e,p=f.cells.length;b<p;b++)e=f.cells[b],g+=e.colSpan;g>n&&(n=g)}return n}function q(a){return function(){var g=this.getValue(),g=!!(CKEDITOR.dialog.validate.integer()(g)&&0<g);g||(alert(a),this.select());return g}}function r(a,g){var n=function(d){return new CKEDITOR.dom.element(d,a.document)};a.editable();return{title:a.lang.table.title,minWidth:310,minHeight:CKEDITOR.env.ie?310:280,onLoad:function(){var d=
this,a=d.getContentElement("advanced","advStyles");if(a)a.on("change",function(){var a=this.getStyle("width",""),b=d.getContentElement("info","txtWidth");b&&b.setValue(a,!0);a=this.getStyle("height","");(b=d.getContentElement("info","txtHeight"))&&b.setValue(a,!0)})},onShow:function(){var d=a.getSelection(),f=d.getRanges(),c,b=this.getContentElement("info","txtRows"),e=this.getContentElement("info","txtCols"),p=this.getContentElement("info","txtWidth"),l=this.getContentElement("info","txtHeight");
"tableProperties"==g&&((d=d.getSelectedElement())&&d.is("table")?c=d:0<f.length&&(CKEDITOR.env.webkit&&f[0].shrink(CKEDITOR.NODE_ELEMENT),c=a.elementPath(f[0].getCommonAncestor(!0)).contains("table",1)),this._.selectedElement=c);c?(this.setupContent(c),b&&b.disable(),e&&e.disable()):(b&&b.enable(),e&&e.enable());p&&p.onChange();l&&l.onChange()},onOk:function(){var d=a.getSelection(),f=this._.selectedElement&&d.createBookmarks(),c=this._.selectedElement||n("table"),b={};this.commitContent(b,c);if(b.info){b=
b.info;if(!this._.selectedElement)for(var e=c.append(n("tbody")),g=parseInt(b.txtRows,10)||0,l=parseInt(b.txtCols,10)||0,k=0;k<g;k++)for(var h=e.append(n("tr")),m=0;m<l;m++)h.append(n("td")).appendBogus();g=b.selHeaders;if(!c.$.tHead&&("row"==g||"both"==g)){h=c.getElementsByTag("thead").getItem(0);e=c.getElementsByTag("tbody").getItem(0);l=e.getElementsByTag("tr").getItem(0);h||(h=new CKEDITOR.dom.element("thead"),h.insertBefore(e));for(k=0;k<l.getChildCount();k++)e=l.getChild(k),e.type!=CKEDITOR.NODE_ELEMENT||
e.data("cke-bookmark")||(e.renameNode("th"),e.setAttribute("scope","col"));h.append(l.remove())}if(null!==c.$.tHead&&"row"!=g&&"both"!=g){h=new CKEDITOR.dom.element(c.$.tHead);e=c.getElementsByTag("tbody").getItem(0);for(m=e.getFirst();0<h.getChildCount();){l=h.getFirst();for(k=0;k<l.getChildCount();k++)e=l.getChild(k),e.type==CKEDITOR.NODE_ELEMENT&&(e.renameNode("td"),e.removeAttribute("scope"));l.insertBefore(m)}h.remove()}if(!this.hasColumnHeaders&&("col"==g||"both"==g))for(h=0;h<c.$.rows.length;h++)e=
new CKEDITOR.dom.element(c.$.rows[h].cells[0]),e.renameNode("th"),e.setAttribute("scope","row");if(this.hasColumnHeaders&&"col"!=g&&"both"!=g)for(k=0;k<c.$.rows.length;k++)h=new CKEDITOR.dom.element(c.$.rows[k]),"tbody"==h.getParent().getName()&&(e=new CKEDITOR.dom.element(h.$.cells[0]),e.renameNode("td"),e.removeAttribute("scope"));b.txtWidth?c.setAttribute("width",b.txtWidth):c.removeAttribute("width");b.txtHeight?c.setAttribute("height",b.txtHeight):c.removeAttribute("height");c.getAttribute("style")||
c.removeAttribute("style")}if(this._.selectedElement)try{d.selectBookmarks(f)}catch(q){}else a.insertElement(c),setTimeout(function(){var d=new CKEDITOR.dom.element(c.$.rows[0].cells[0]),b=a.createRange();b.moveToPosition(d,CKEDITOR.POSITION_AFTER_START);b.select()},0)},contents:[{id:"info",label:a.lang.table.title,elements:[{type:"hbox",widths:[null,null],styles:["vertical-align:top"],children:[{type:"vbox",padding:0,children:[{type:"text",id:"txtRows","default":3,label:a.lang.table.rows,required:!0,
controlStyle:"width:5em",validate:q(a.lang.table.invalidRows),setup:function(d){this.setValue(d.$.rows.length)},commit:m},{type:"text",id:"txtCols","default":2,label:a.lang.table.columns,required:!0,controlStyle:"width:5em",validate:q(a.lang.table.invalidCols),setup:function(d){this.setValue(u(d))},commit:m},{type:"html",html:"\x26nbsp;"},{type:"select",id:"selHeaders",requiredContent:"th","default":"",label:a.lang.table.headers,items:[[a.lang.table.headersNone,""],[a.lang.table.headersRow,"row"],
[a.lang.table.headersColumn,"col"],[a.lang.table.headersBoth,"both"]],setup:function(d){var a=this.getDialog();a.hasColumnHeaders=!0;for(var c=0;c<d.$.rows.length;c++){var b=d.$.rows[c].cells[0];if(b&&"th"!=b.nodeName.toLowerCase()){a.hasColumnHeaders=!1;break}}null!==d.$.tHead?this.setValue(a.hasColumnHeaders?"both":"row"):this.setValue(a.hasColumnHeaders?"col":"")},commit:m},{type:"text",id:"txtBorder",requiredContent:"table[border]","default":a.filter.check("table[border]")?1:0,label:a.lang.table.border,
controlStyle:"width:3em",validate:CKEDITOR.dialog.validate.number(a.lang.table.invalidBorder),setup:function(a){this.setValue(a.getAttribute("border")||"")},commit:function(a,f){this.getValue()?f.setAttribute("border",this.getValue()):f.removeAttribute("border")}},{id:"cmbAlign",type:"select",requiredContent:"table[align]","default":"",label:a.lang.common.align,items:[[a.lang.common.notSet,""],[a.lang.common.alignLeft,"left"],[a.lang.common.alignCenter,"center"],[a.lang.common.alignRight,"right"]],
setup:function(a){this.setValue(a.getAttribute("align")||"")},commit:function(a,f){this.getValue()?f.setAttribute("align",this.getValue()):f.removeAttribute("align")}}]},{type:"vbox",padding:0,children:[{type:"hbox",widths:["5em"],children:[{type:"text",id:"txtWidth",requiredContent:"table{width}",controlStyle:"width:5em",label:a.lang.common.width,title:a.lang.common.cssLengthTooltip,"default":"100%",getValue:t,validate:CKEDITOR.dialog.validate.cssLength(a.lang.common.invalidCssLength.replace("%1",
a.lang.common.width)),onChange:function(){var a=this.getDialog().getContentElement("advanced","advStyles");a&&a.updateStyle("width",this.getValue())},setup:function(a){a=a.getAttribute("width");this.setValue(a)},commit:m}]},{type:"hbox",widths:["5em"],children:[{type:"text",id:"txtHeight",controlStyle:"width:5em",label:a.lang.common.height,title:a.lang.common.cssLengthTooltip,"default":"",getValue:t,validate:CKEDITOR.dialog.validate.cssLength(a.lang.common.invalidCssLength.replace("%1",a.lang.common.height)),
onChange:function(){var a=this.getDialog().getContentElement("advanced","advStyles");a&&a.updateStyle("height",this.getValue())},setup:function(a){(a=a.getAttribute("height"))&&this.setValue(a)},commit:m}]},{type:"html",html:"\x26nbsp;"},{type:"text",id:"txtCellSpace",requiredContent:"table[cellspacing]",controlStyle:"width:3em",label:a.lang.table.cellSpace,"default":"0",validate:CKEDITOR.dialog.validate.number(a.lang.table.invalidCellSpacing),setup:function(a){this.setValue(a.getAttribute("cellSpacing")||
"")},commit:function(a,f){this.getValue()?f.setAttribute("cellSpacing",this.getValue()):f.removeAttribute("cellSpacing")}},{type:"text",id:"txtCellPad",requiredContent:"table[cellpadding]",controlStyle:"width:3em",label:a.lang.table.cellPad,"default":a.filter.check("table[cellpadding]")?1:0,validate:CKEDITOR.dialog.validate.number(a.lang.table.invalidCellPadding),setup:function(a){this.setValue(a.getAttribute("cellPadding")||"")},commit:function(a,f){this.getValue()?f.setAttribute("cellPadding",this.getValue()):
f.removeAttribute("cellPadding")}}]}]},{type:"html",align:"right",html:""},{type:"vbox",padding:0,children:[{type:"text",id:"txtCaption",requiredContent:"caption",label:a.lang.table.caption,setup:function(a){this.enable();a=a.getElementsByTag("caption");if(0<a.count()){a=a.getItem(0);var f=a.getFirst(CKEDITOR.dom.walker.nodeType(CKEDITOR.NODE_ELEMENT));f&&!f.equals(a.getBogus())?(this.disable(),this.setValue(a.getText())):(a=CKEDITOR.tools.trim(a.getText()),this.setValue(a))}},commit:function(d,f){if(this.isEnabled()){var c=
this.getValue(),b=f.getElementsByTag("caption");if(c)0<b.count()?(b=b.getItem(0),b.setHtml("")):(b=new CKEDITOR.dom.element("caption",a.document),f.append(b,!0)),b.append(new CKEDITOR.dom.text(c,a.document));else if(0<b.count())for(c=b.count()-1;0<=c;c--)b.getItem(c).remove()}}}]}]}]}}var t=CKEDITOR.tools.cssLength,m=function(a){var g=this.id;a.info||(a.info={});a.info[g]=this.getValue()};CKEDITOR.dialog.add("table",function(a){return r(a,"table")});CKEDITOR.dialog.add("tableProperties",function(a){return r(a,
"tableProperties")})})();