/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
(function(){function u(a){for(var b=0,m=0,h=0,e,n=a.$.rows.length;h<n;h++){e=a.$.rows[h];for(var c=b=0,d,f=e.cells.length;c<f;c++)d=e.cells[c],b+=d.colSpan;b>m&&(m=b)}return m}function q(a){return function(){var b=this.getValue(),b=!!(CKEDITOR.dialog.validate.integer()(b)&&0<b);b||(alert(a),this.select());return b}}function p(a,b){var m=function(e){return new CKEDITOR.dom.element(e,a.document)},p=a.editable();return{title:a.lang.table.title,minWidth:310,minHeight:CKEDITOR.env.ie?310:280,onLoad:function(){var e=
this,a=e.getContentElement("advanced","advStyles");if(a)a.on("change",function(){var a=this.getStyle("width",""),d=e.getContentElement("info","txtWidth");d&&d.setValue(a,!0);a=this.getStyle("height","");(d=e.getContentElement("info","txtHeight"))&&d.setValue(a,!0)})},onShow:function(){var e=a.getSelection(),n=e.getRanges(),c,d=this.getContentElement("info","txtRows"),f=this.getContentElement("info","txtCols"),r=this.getContentElement("info","txtWidth"),l=this.getContentElement("info","txtHeight");
"tableProperties"==b&&((e=e.getSelectedElement())&&e.is("table")?c=e:0<n.length&&(CKEDITOR.env.webkit&&n[0].shrink(CKEDITOR.NODE_ELEMENT),c=a.elementPath(n[0].getCommonAncestor(!0)).contains("table",1)),this._.selectedElement=c);c?(this.setupContent(c),d&&d.disable(),f&&f.disable()):(d&&d.enable(),f&&f.enable());r&&r.onChange();l&&l.onChange()},onOk:function(){var e=a.getSelection(),n=this._.selectedElement&&e.createBookmarks(),c=this._.selectedElement||m("table"),d={};this.commitContent(d,c);if(d.info){d=
d.info;if(!this._.selectedElement)for(var f=c.append(m("tbody")),b=parseInt(d.txtRows,10)||0,l=parseInt(d.txtCols,10)||0,k=0;k<b;k++)for(var g=f.append(m("tr")),h=0;h<l;h++)g.append(m("td")).appendBogus();b=d.selHeaders;if(!c.$.tHead&&("row"==b||"both"==b)){g=c.getElementsByTag("thead").getItem(0);f=c.getElementsByTag("tbody").getItem(0);l=f.getElementsByTag("tr").getItem(0);g||(g=new CKEDITOR.dom.element("thead"),g.insertBefore(f));for(k=0;k<l.getChildCount();k++)f=l.getChild(k),f.type!=CKEDITOR.NODE_ELEMENT||
f.data("cke-bookmark")||(f.renameNode("th"),f.setAttribute("scope","col"));g.append(l.remove())}if(null!==c.$.tHead&&"row"!=b&&"both"!=b){g=new CKEDITOR.dom.element(c.$.tHead);f=c.getElementsByTag("tbody").getItem(0);for(h=f.getFirst();0<g.getChildCount();){l=g.getFirst();for(k=0;k<l.getChildCount();k++)f=l.getChild(k),f.type==CKEDITOR.NODE_ELEMENT&&(f.renameNode("td"),f.removeAttribute("scope"));l.insertBefore(h)}g.remove()}if(!this.hasColumnHeaders&&("col"==b||"both"==b))for(g=0;g<c.$.rows.length;g++)f=
new CKEDITOR.dom.element(c.$.rows[g].cells[0]),f.renameNode("th"),f.setAttribute("scope","row");if(this.hasColumnHeaders&&"col"!=b&&"both"!=b)for(k=0;k<c.$.rows.length;k++)g=new CKEDITOR.dom.element(c.$.rows[k]),"tbody"==g.getParent().getName()&&(f=new CKEDITOR.dom.element(g.$.cells[0]),f.renameNode("td"),f.removeAttribute("scope"));d.txtWidth?c.setAttribute("width",d.txtWidth):c.removeAttribute("width");d.txtHeight?c.setAttribute("height",d.txtHeight):c.removeAttribute("height");c.getAttribute("style")||
c.removeAttribute("style")}if(this._.selectedElement)try{e.selectBookmarks(n)}catch(p){}else a.insertElement(c),setTimeout(function(){var e=new CKEDITOR.dom.element(c.$.rows[0].cells[0]),d=a.createRange();d.moveToPosition(e,CKEDITOR.POSITION_AFTER_START);d.select()},0)},contents:[{id:"info",label:a.lang.table.title,elements:[{type:"hbox",widths:[null,null],styles:["vertical-align:top"],children:[{type:"vbox",padding:0,children:[{type:"text",id:"txtRows","default":3,label:a.lang.table.rows,required:!0,
controlStyle:"width:5em",validate:q(a.lang.table.invalidRows),setup:function(e){this.setValue(e.$.rows.length)},commit:h},{type:"text",id:"txtCols","default":2,label:a.lang.table.columns,required:!0,controlStyle:"width:5em",validate:q(a.lang.table.invalidCols),setup:function(e){this.setValue(u(e))},commit:h},{type:"html",html:"\x26nbsp;"},{type:"select",id:"selHeaders",requiredContent:"th","default":"",label:a.lang.table.headers,items:[[a.lang.table.headersNone,""],[a.lang.table.headersRow,"row"],
[a.lang.table.headersColumn,"col"],[a.lang.table.headersBoth,"both"]],setup:function(e){var a=this.getDialog();a.hasColumnHeaders=!0;for(var c=0;c<e.$.rows.length;c++){var d=e.$.rows[c].cells[0];if(d&&"th"!=d.nodeName.toLowerCase()){a.hasColumnHeaders=!1;break}}null!==e.$.tHead?this.setValue(a.hasColumnHeaders?"both":"row"):this.setValue(a.hasColumnHeaders?"col":"")},commit:h},{type:"text",id:"txtBorder",requiredContent:"table[border]","default":a.filter.check("table[border]")?1:0,label:a.lang.table.border,
controlStyle:"width:3em",validate:CKEDITOR.dialog.validate.number(a.lang.table.invalidBorder),setup:function(a){this.setValue(a.getAttribute("border")||"")},commit:function(a,b){this.getValue()?b.setAttribute("border",this.getValue()):b.removeAttribute("border")}},{id:"cmbAlign",type:"select",requiredContent:"table[align]","default":"",label:a.lang.common.align,items:[[a.lang.common.notSet,""],[a.lang.common.alignLeft,"left"],[a.lang.common.alignCenter,"center"],[a.lang.common.alignRight,"right"]],
setup:function(a){this.setValue(a.getAttribute("align")||"")},commit:function(a,b){this.getValue()?b.setAttribute("align",this.getValue()):b.removeAttribute("align")}}]},{type:"vbox",padding:0,children:[{type:"hbox",widths:["5em"],children:[{type:"text",id:"txtWidth",requiredContent:"table{width}",controlStyle:"width:5em",label:a.lang.common.width,title:a.lang.common.cssLengthTooltip,"default":a.filter.check("table{width}")?500>p.getSize("width")?"100%":500:0,getValue:t,validate:CKEDITOR.dialog.validate.cssLength(a.lang.common.invalidCssLength.replace("%1",
a.lang.common.width)),onChange:function(){var a=this.getDialog().getContentElement("advanced","advStyles");a&&a.updateStyle("width",this.getValue())},setup:function(a){a=a.getAttribute("width");this.setValue(a)},commit:h}]},{type:"hbox",widths:["5em"],children:[{type:"text",id:"txtHeight",requiredContent:"table{height}",controlStyle:"width:5em",label:a.lang.common.height,title:a.lang.common.cssLengthTooltip,"default":"",getValue:t,validate:CKEDITOR.dialog.validate.cssLength(a.lang.common.invalidCssLength.replace("%1",
a.lang.common.height)),onChange:function(){var a=this.getDialog().getContentElement("advanced","advStyles");a&&a.updateStyle("height",this.getValue())},setup:function(a){(a=a.getAttribute("height"))&&this.setValue(a)},commit:h}]},{type:"html",html:"\x26nbsp;"},{type:"text",id:"txtCellSpace",requiredContent:"table[cellspacing]",controlStyle:"width:3em",label:a.lang.table.cellSpace,"default":a.filter.check("table[cellspacing]")?1:0,validate:CKEDITOR.dialog.validate.number(a.lang.table.invalidCellSpacing),
setup:function(a){this.setValue(a.getAttribute("cellSpacing")||"")},commit:function(a,b){this.getValue()?b.setAttribute("cellSpacing",this.getValue()):b.removeAttribute("cellSpacing")}},{type:"text",id:"txtCellPad",requiredContent:"table[cellpadding]",controlStyle:"width:3em",label:a.lang.table.cellPad,"default":a.filter.check("table[cellpadding]")?1:0,validate:CKEDITOR.dialog.validate.number(a.lang.table.invalidCellPadding),setup:function(a){this.setValue(a.getAttribute("cellPadding")||"")},commit:function(a,
b){this.getValue()?b.setAttribute("cellPadding",this.getValue()):b.removeAttribute("cellPadding")}}]}]},{type:"html",align:"right",html:""},{type:"vbox",padding:0,children:[{type:"text",id:"txtCaption",requiredContent:"caption",label:a.lang.table.caption,setup:function(a){this.enable();a=a.getElementsByTag("caption");if(0<a.count()){a=a.getItem(0);var b=a.getFirst(CKEDITOR.dom.walker.nodeType(CKEDITOR.NODE_ELEMENT));b&&!b.equals(a.getBogus())?(this.disable(),this.setValue(a.getText())):(a=CKEDITOR.tools.trim(a.getText()),
this.setValue(a))}},commit:function(b,h){if(this.isEnabled()){var c=this.getValue(),d=h.getElementsByTag("caption");if(c)0<d.count()?(d=d.getItem(0),d.setHtml("")):(d=new CKEDITOR.dom.element("caption",a.document),h.append(d,!0)),d.append(new CKEDITOR.dom.text(c,a.document));else if(0<d.count())for(c=d.count()-1;0<=c;c--)d.getItem(c).remove()}}}]}]}]}}var t=CKEDITOR.tools.cssLength,h=function(a){var b=this.id;a.info||(a.info={});a.info[b]=this.getValue()};CKEDITOR.dialog.add("table",function(a){return p(a,
"table")});CKEDITOR.dialog.add("tableProperties",function(a){return p(a,"tableProperties")})})();